# TensorFlow tutorials kick-start

### Hello World program

In [1]:
import tensorflow as tf
hello = tf.constant('Hello world, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

b'Hello world, TensorFlow!'


### Some Math Operations

In [2]:
a = tf.constant(7.0)
b = tf.constant(2.0)
c = a + b
print(c)

Tensor("add:0", shape=(), dtype=float32)


In [3]:
sess = tf.Session()
print(sess.run(c))

9.0


In [4]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 3
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.5416826  0.97111404 0.54064584]
[0.21443152 0.7062371  0.37150908]
(array([1.3310572, 1.2585932, 1.4826521], dtype=float32), array([3.331057 , 3.258593 , 3.4826522], dtype=float32))


### Feeding

In [5]:
w = tf.placeholder(tf.float32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y * w

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = a + b

In [6]:
print(sess.run(z, feed_dict= { w:2, x:100, y:3.5 }))
print(sess.run(c, feed_dict= { a:[1,2,3], b: [3,4,5]}))

107.0
[4. 6. 8.]


### Datasets

In [7]:
my_data = [
    [0, 1, 5],
    [2, 3, 9],
    [4, 5, 8],
    [6, 7, 10],
]

slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1 5]
[2 3 9]
[4 5 8]
[ 6  7 10]


In [8]:
a = tf.constant([1,2,3], shape=[2,3], name="a")
b= tf.constant([4,5,6], shape=[3,2], name="b")
print(sess.run(tf.matmul(a,b)))

[[34 35]
 [48 51]]


 ### sklearn

In [9]:
from sklearn import datasets
import pandas as pd

In [10]:
iris = datasets.load_iris()

print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### matmul test

In [18]:
a = tf.constant([1,2,3], shape=[1,3], name="a")
b = tf.constant([4,5,6], shape=[3,1], name="b")

sess.run(a @ b @ a)

array([[32, 64, 96]], dtype=int32)